name: Basic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: List files
      run: ls -R

    - name: Check README_BACKUP.md exists
      run: test -f backup/README_BACKUP.md

    - name: Run backup script
      run: bash backup.sh
	
    - name: Say Hello
      run: echo "🎉 Hello from CI/CD! Your code was pushed successfully."
